# Generated by Django 3.0.6 on 2020-06-22 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20200621_1758'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
